CREATE DATABASE customer_analysis_db;
SHOW DATABASES;
USE customer_analysis_db;

SHOW TABLES;
SELECT * 
FROM customer_shopping_behavior;

USE customer_analysis_db;

DESCRIBE customer_shopping_behavior;

USE customer_analysis_db;

-- --Q1. What is the total revenue generated by male vs. female customers?
    
    select gender,sum(purchase_amount) as Revenue
    from customer_shopping_behavior
    group by gender;
     
-- --Q2. Which customers used a discount but still spent more than the average purchase amount? 
        
        select customer_id, purchase_amount
        from customer_shopping_behavior
        where  discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer_shopping_behavior);
      
-- -- Q3. Which are the top 5 products with the highest average review rating?
          
          select item_purchased,round(avg(review_rating),2)as avg_product_rating
           from customer_shopping_behavior
          group by item_purchased
          order by avg_product_rating desc
          limit 5;
         
	-- --Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
        select shipping_type, round(avg(purchase_amount),2) as Avg_purchase_amount
        from customer_shopping_behavior
        where shipping_type in ('Standard','Express')
        group by shipping_type ;
        
        
-- --Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- --between subscribers and non-subscribers.
  select  count(customer_id) as total_customers,subscription_status, round(avg(purchase_amount),2)as average_spend,sum(purchase_amount) as total_revenue 
   from customer_shopping_behavior
   group by subscription_status
   order by average_spend,total_revenue desc;

-- --Q6. Which 5 products have the highest percentage of purchases with discounts applied?
 select item_purchased,
 round(sum(case when discount_applied='Yes' then 1 else 0 end)*100.0/count(*),2) as discount_percentage
from customer_shopping_behavior
group by item_purchased
order by discount_percentage desc
limit 5;
-- --Q7. Segment customers into New, Returning, and Loyal based on their total 
-- -- number of previous purchases, and show the count of each segment.
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        WHEN previous_purchases > 5 THEN 'Loyal'
    END AS customer_segment,
    COUNT(*) AS no_of_customers
FROM customer_shopping_behavior
GROUP BY customer_segment;

-- --Q8. What are the top 3 most purchased products within each category? 

  with item_sales as(
  select item_purchased, category,
  count(*) as  purchase_count,
  row_number() OVER (PARTITION BY category order by count(*) desc) as ranking
  FROM customer_shopping_behavior
  group by item_purchased, category)
  
  select * 
  from item_sales
  where ranking <=3;
-- --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
    SELECT subscription_status, Count(customer_id) as repeat_buyer
     FROM customer_shopping_behavior
    where previous_purchases>5
    group by subscription_status;
-- --Q10. What is the revenue contribution of each age group? 
select age_group ,sum(purchase_amount) as totl_revenue
FROM customer_shopping_behavior
group by age_group
order by totl_revenue desc;












